### ISSUE TITLE
Intelligent Claim Receipt System: system should not allow invalid claims

### ISSUE THREAD

**Issue by epfindia** [epfindia/epfindia.github.io#8]
invalid   claims like must not be allowed eg no pension claim for less than 6 month   service shall be allowed.

**Comment by vivekgupta-epf** [comment]
No claim if acct balance is zero

**Comment by epfindia** [comment]
The DA Receipt is given too many things to check which is humanly error prone. The current system essentially makes the work of DA receipt Subjective and time-consuming. Most of the rejected cases in all the field offices can be stopped before receipt but the system doesn't show any intelligence. First DA receipt has to check the eligibility of case by downloading member ledger and KYC details and then start entering the claim. 

If at "Claim entry stage" following workflow is used the claim filing process can become easier and rejection ratio of all the offices zero.

1. Entering of UAN/PF code and enter claim type
2,. System can then fetch information and check eligibility of member for that claim.
3. if member is eligible-> auto fill all the details which is available in the database
4. if member is ineligible -> show the reasons of ineligibility (else show warnings and proceed to next step)
5. Show other fields which require manual entry.
6. Submit.

This would reduce the time required by DA receipt by 90% and rejected claims by almost 100%.

**Comment by epfindia** [comment]
![whatsapp image 2018-03-10 at 10 46 00 pm](https://user-images.githubusercontent.com/32270777/37244856-14aba4f0-24b5-11e8-92f1-4975a75272d0.jpeg)

**Comment by epfindia** [comment]
closing the issue for better summary
